# Generated by Django 6.0.2 on 2026-02-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('de', 'Deutsch'), ('es', 'Español')], default='fr', max_length=2),
        ),
    ]
