# Generated by Django 6.0.5 on 2026-06-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_supportmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_doc_back',
            field=models.ImageField(blank=True, upload_to='ids/back/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_doc_front',
            field=models.ImageField(blank=True, upload_to='ids/front/'),
        ),
    ]
