# Generated by Django 6.0.6 on 2026-06-04 22:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_make_id_docs_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='bank.beneficiary'),
        ),
    ]
